name: Deploy Sub White Label
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    if: ${{ contains(github.event.head_commit.message, '--deploy') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: github_action
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Setup Go environment
        uses: actions/setup-go@v4.0.1
        with:
          go-version: "1.21.1"
          cache-dependency-path: source/go.sum

      - name: Build GO
        run: |
          cd source/apps/aff-api
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o aff-api main.go

      - name: Copy File Build to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: aff
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ./source/apps/aff-api/aff-api
          target: /home/aff/go/arb-backend/

      - name: Copy File Docs to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: aff
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ./source/apps/aff-api/docs
          target: /home/aff/go/arb-backend/

      - name: Run command on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: aff
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/aff/go/arb-backend
            supervisorctl -c /usr/share/supervisor/aff/supervisord.conf restart AffAPI

  notify-telegram:
    needs: [build-and-deploy]
    runs-on: ubuntu-latest
    if: ${{ always() && needs.build-and-deploy.result != 'skipped' }}
    steps:
      - name: Send notification to Telegram Bot
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHATID_TELEGRAM_ARBDEV }}
          token: ${{ secrets.BOTID_TELEGRAM_PUBPOWER }}
          message: |
            [${{ needs.build-and-deploy.result }}] ${{ github.workflow }} - ${{ github.repository }}
            Created by: ${{ github.actor }}
            See details: [GitHub Actions Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
