name: Deploy Sub White Label
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    if: ${{ contains(github.event.head_commit.message, '--deploy') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: github_action
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Setup Go environment
        uses: actions/setup-go@v4.0.1
        with:
          go-version: "1.21.1"
          cache-dependency-path: source/go.sum

      - name: Install dependencies
        run: |
          go mod tidy
          go mod vendor

      - name: Build GO
        run: |
          cd source/apps/frontend
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o frontend main.go
#          cd /home/assyrian/go/pubpower-subpub/source/apps/frontend/view
#          npm install
#          npm run build

      - name: Copy File Build to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: assyrian
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ./source/apps/frontend/frontend
          target: /home/assyrian/go/pubpower-subpub/

      - name: Copy to PubPower Sub Pub
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: assyrian
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./"
          target: /home/assyrian/go/pubpower-subpub1/

      - name: Run command on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: assyrian
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/assyrian/go/pubpower-subpub
            supervisorctl -c /usr/share/supervisor/assyrian/supervisord.conf restart frontend

  notify-telegram:
    needs: [ build-and-deploy ]
    runs-on: ubuntu-latest
    if: ${{ always() && needs.build-and-deploy.result != 'skipped' }}
    steps:
      - name: Send notification to Telegram Bot
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHATID_TELEGRAM }}
          token: ${{ secrets.BOTID_TELEGRAM_PUBPOWER }}
          message: |
            [${{ needs.build-and-deploy.result }}] ${{ github.workflow }} - ${{ github.repository }}
            Created by: ${{ github.actor }}
            See details: [GitHub Actions Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
